<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */



//remove_action( 'genesis_loop', 'genesis_do_loop' );
//add_action( 'genesis_loop', 'get_categoryloop' );
//
//function get_categoryloop() {
//
//    $year = get_query_var('year');
//    $monthnum  = get_query_var('monthnum');
//
//    if ($year) {
//        $out = do_shortcode('[showPosts year="'.$year.'" month="'.$monthnum .'"]');
//    }
//    echo 'archive.php'.$out;
//}


// This file handles single entries, but only exists for the sake of child theme forward compatibility.
genesis();