<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */



remove_action( 'genesis_loop', 'genesis_do_loop' );


remove_action( 'genesis_before_loop', 'genesis_do_taxonomy_title_description', 15 );

add_action( 'genesis_loop', 'get_categoryloop' );

function get_categoryloop() {

    $page_object = get_queried_object();
    $cat = $page_object->cat_ID;

    /* get all terms  */
    $terms = get_terms( array(
        'taxonomy' => 'category'
    ) );
    $out = '<div class="row blogfilter"><span>'.__( 'Filter by:', 'doering' ).'</span><ul>';
	$out .= '<li><a class="all" href="'.get_the_permalink(419).'">'.__( 'Display all', 'doering' ).'</a></li>';
    foreach ($terms as $k => $v) {
        if ($v->term_id == $page_object->cat_ID) {
            $class = 'active';
        } else {
            $class = '';
        }
        $term_link = get_term_link($v);
        $out .= '<li><a class="'.$class.' " href="'.$term_link.'">'.$v->name.'</a></li>';
    }
    $out .= '</ul></div>';

    if ($cat) {
        $out .= do_shortcode('[showPosts catid="'.$cat.'"]');
    }
    echo $out;
}


// This file handles single entries, but only exists for the sake of child theme forward compatibility.
genesis();


